# Travis-CI.org build script

# container-based infrastructure
#sudo: false
# need APT packages to get white-listed first;
sudo: required

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libnetpbm10 libnetpbm10-dev wcslib-dev libcfitsio3 libcfitsio3-dev python-numpy swig gsl-bin libgsl0-dev python-sphinx sphinx-common

language: c
compiler:
  - gcc
  - clang

#script: export NETPBM_INC="-I$(pwd)"; export WCSLIB_INC="-I/usr/include/wcslib-4.8.3"; export WCSLIB_LIB="-lwcs" && git clone https://github.com/dstndstn/astrometry.net.git && (cd astrometry.net && ln -s /usr/include netpbm && make && make py) && git clone https://github.com/dstndstn/tractor.git tractor-git && (cd tractor-git && make) && ln -s astrometry.net astrometry && ln -s tractor-git/tractor . && ln -s tractor-git/tractor/utils . && ln -s tractor-git/tractor/wise . && (cd doc && make)

before_script:
    - export NETPBM_INC="-I$(pwd)"
    - export WCSLIB_INC="-I/usr/include/wcslib-4.8.3"
    - export WCSLIB_LIB="-lwcs"
    - pkg-config --exists gsl
    - pkg-config --modversion gsl
    - export SYSTEM_GSL=yes
    - ls /usr/include/wcslib*
    - if [ ! -d "$HOME/astrometry.net" ]; then (cd $HOME; git clone https://github.com/dstndstn/astrometry.net.git); fi
    - (cd $HOME/astrometry.net && ln -s /usr/include netpbm && make && make py)
    - ln -s $HOME/astrometry.net astrometry
    - if [ ! -d "$HOME/tractor-git" ]; then (cd $HOME; git clone https://github.com/dstndstn/tractor.git tractor-git); fi
    - (cd $HOME/tractor-git && make)
    - ln -s $HOME/tractor-git/tractor/tractor .
    - ln -s $HOME/tractor-git/tractor/utils .
    - ln -s $HOME/tractor-git/tractor/wise .

script:
    - pwd
    - ls
    - echo $HOME
    - ls $HOME
    - export PYTHONPATH=${PYTHONPATH}:py
    - ls -l
    - (cd doc && make)

addons:
  apt:
    packages:
    - libnetpbm10
    - libnetpbm10-dev
    - wcslib-dev
    - libcfitsio3
    - libcfitsio3-dev
    - python-numpy
    - swig
    - gsl-bin
    - libgsl10-dev

cache:
  directories:
  - $HOME/astrometry.net
  - $HOME/tractor-git
