# Travis-CI.org build script

# Default environment is Ubuntu 12.04.5 LTS "precise"
# which is pretty old.
# "trusty" is Ubuntu 14.04.5 LTS
dist: trusty

# use the newer container-based infrastructure
sudo: false

# python versions to test against...
language: python
python:
  - "2.7"
  - "3.6"

install:
    - export WCSLIB_INC="-I/usr/include/wcslib-4.20"
    - export WCSLIB_LIB="-lwcs"

    - pip install jinja2
    - python -c "import jinja2"
    - python -c "from jinja2.utils import Markup"
    - pip install numpy
    - pip install scipy
    - pip install matplotlib
    - pip install numpydoc
    - pip install astropy
    - pip install Sphinx
    - pip install photutils
    - pip install coveralls
    # fitsio master version
    - pip install --no-deps --upgrade git+https://github.com/esheldon/fitsio.git#egg=fitsio
    - pip install -v --no-deps --upgrade git+https://github.com/dstndstn/tractor.git

before_script:
    - if [ ! -d "$HOME/astrometry.net" ]; then (cd $HOME; git clone https://github.com/dstndstn/astrometry.net.git); fi
    - (cd $HOME/astrometry.net && git pull) || (rm -Rf $HOME/astrometry.net && cd $HOME && git clone https://github.com/dstndstn/astrometry.net.git);
    - (cd $HOME/astrometry.net && make && make py)

    # - if [ ! -d "$HOME/tractor-git" ]; then (cd $HOME; git clone https://github.com/dstndstn/tractor.git tractor-git); fi
    # - (cd $HOME/tractor-git && git pull) || (rm -Rf $HOME/tractor-git && cd $HOME && git clone https://github.com/dstndstn/tractor.git tractor-git);
    # - (cd $HOME/tractor-git && make)
    # - ln -s $HOME/tractor-git/tractor .
    # - ln -s $HOME/tractor-git/wise .

    # pip install fitsio instead
    #- if [ ! -d "$HOME/fitsio-git" ]; then (cd $HOME; git clone https://github.com/esheldon/fitsio.git fitsio-git); fi
    #- (cd $HOME/fitsio-git && git pull) || (rm -Rf $HOME/fitsio-git && cd $HOME && git clone https://github.com/esheldon/fitsio.git fitsio-git);
    #- (rm -Rf $HOME/fitsio-git && cd $HOME && git clone https://github.com/esheldon/fitsio.git fitsio-git);
    #- (cd $HOME/fitsio-git && python setup.py install --home $HOME/fitsio)
    #- ln -s $HOME/fitsio/lib/python/fitsio .

    - mkdir -p $HOME/dust/maps
    - (cd $HOME/dust/maps && wget -c http://portal.nersc.gov/project/cosmo/temp/dstn/travis-ci/maps/SFD_dust_4096_ngp.fits)
    - (cd $HOME/dust/maps && wget -c http://portal.nersc.gov/project/cosmo/temp/dstn/travis-ci/maps/SFD_dust_4096_sgp.fits)
    - export DUST_DIR=$HOME/dust

script:
    - export PYTHONPATH=${PYTHONPATH}:$(pwd)/py:$HOME/astrometry.net
    - ls $HOME
    - ls $HOME/astrometry.net
    - (cd doc && make)
    - echo $PYTHONPATH
    - python -c "import numpy; print(numpy.__file__)"
    - python -c "import matplotlib; print(matplotlib.__file__)"
    - python -c "import fitsio; print(fitsio.__file__)"
    - python -c "import tractor.emfit"
    # - find /home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/tractor -type f
    # - find /home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/tractor -type f
    - (cd py && coverage run test/runbrick_test.py travis)

after_success:
    - (cd py && coveralls debug)
    - (cd py && coveralls)

addons:
  apt:
    packages:
    - libnetpbm10
    - libnetpbm10-dev
    - wcslib-dev
    - libcfitsio3
    - libcfitsio3-dev
    - swig
    - gsl-bin
    - libgsl0-dev

cache:
  directories:
  - $HOME/astrometry.net
  - $HOME/dust
