# Travis-CI.org build script

# Default environment is Ubuntu 12.04.5 LTS "precise"
# which is pretty old.
# "trusty" is Ubuntu 14.04.5 LTS
#dist: trusty
dist: xenial

# use the newer container-based infrastructure
sudo: false

# python versions to test against...
language: python
python:
  - "3.6"
  - "3.7"
#  - "3.8"

install:
    - export WCSLIB_INC="-I/usr/include/wcslib-4.20"
    - export WCSLIB_LIB="-lwcs"

    - pip install Sphinx #==1.5.4   # 1.5.6?
    - pip install numpy
    - pip install scipy
    - pip install Pillow
    - pip install matplotlib
    - pip install numpydoc
    - pip install astropy #==2.0rc1
    - pip install photutils
    - pip install coveralls
    - pip install fitsio==1.1.1
    #- pip install --no-deps --upgrade git+https://github.com/esheldon/fitsio.git@v0.9.12#egg=fitsio
    #- pip install -v --no-deps --upgrade git+https://github.com/dstndstn/tractor.git@cython
    - pip install cython
    - git clone https://github.com/dstndstn/tractor.git
    - (cd tractor && python setup-cython.py install)

before_script:
    - if [ ! -d "$HOME/astrometry.net" ]; then (cd $HOME; git clone https://github.com/dstndstn/astrometry.net.git); fi
    - (cd $HOME/astrometry.net && git pull) || (rm -Rf $HOME/astrometry.net && cd $HOME && git clone https://github.com/dstndstn/astrometry.net.git);
    - (cd $HOME/astrometry.net && make && make py)

    - (cd $HOME && git clone https://github.com/legacysurvey/unwise_psf.git && cd unwise_psf && git checkout dr9.2)

    - mkdir -p $HOME/dust/maps
    - (cd $HOME/dust/maps && wget -c http://portal.nersc.gov/project/cosmo/temp/dstn/travis-ci/maps/SFD_dust_4096_ngp.fits)
    - (cd $HOME/dust/maps && wget -c http://portal.nersc.gov/project/cosmo/temp/dstn/travis-ci/maps/SFD_dust_4096_sgp.fits)
    - export DUST_DIR=$HOME/dust

script:
    - export PYTHONPATH=${PYTHONPATH}:$(pwd)/py:$HOME/astrometry.net:$HOME/unwise_psf/py
    - ls $HOME
    - ls $HOME/astrometry.net
    - (cd doc && make)
    - (cd py && coverage run test/runbrick_test.py travis && coverage run -a test/unit_tests.py)

after_success:
    - (cd py && coveralls debug)
    - (cd py && coveralls)

addons:
  apt:
    packages:
    - libnetpbm10
    - libnetpbm10-dev
    - netpbm
    - wcslib-dev
    - libcfitsio3
    - libcfitsio3-dev
    - swig
    - gsl-bin
    - libgsl0-dev

cache:
  directories:
  - $HOME/astrometry.net
  - $HOME/dust
