# Travis-CI.org build script

# container-based infrastructure
sudo: false

# install:
#   - sudo apt-get update -qq
#   - sudo apt-get install -y libnetpbm10 libnetpbm10-dev wcslib-dev libcfitsio3 libcfitsio3-dev python-numpy swig gsl-bin libgsl0-dev python-sphinx sphinx-common python-matplotlib python-scipy python-mock 
#   - sudo pip install numpydoc
# # python-numpydoc -- not available until Ubuntu 14.04 trusty

install:
    - pip install --user numpy
    - pip install numpydoc -t $HOME/numpydoc
    - pip install --user coveralls
    - pip install --user astropy

language: c
compiler:
    - gcc

before_script:
    - export WCSLIB_INC="-I/usr/include/wcslib-4.8.3"
    - export WCSLIB_LIB="-lwcs"
    - if [ ! -d "$HOME/astrometry.net" ]; then (cd $HOME; git clone https://github.com/dstndstn/astrometry.net.git); fi
    - (cd $HOME/astrometry.net && git pull) || (rm -Rf $HOME/astrometry.net && cd $HOME && git clone https://github.com/dstndstn/astrometry.net.git);
    - (cd $HOME/astrometry.net && make && make py)
    - if [ ! -d "$HOME/tractor-git" ]; then (cd $HOME; git clone https://github.com/dstndstn/tractor.git tractor-git); fi
    - (cd $HOME/tractor-git && git pull) || (rm -Rf $HOME/tractor-git && cd $HOME && git clone https://github.com/dstndstn/tractor.git tractor-git);
    - (cd $HOME/tractor-git && make)
    - if [ ! -d "$HOME/fitsio-git" ]; then (cd $HOME; git clone https://github.com/esheldon/fitsio.git fitsio-git); fi
    - (cd $HOME/fitsio-git && git pull) || (rm -Rf $HOME/fitsio-git && cd $HOME && git clone https://github.com/esheldon/fitsio.git fitsio-git);
    - (cd $HOME/fitsio-git && python setup.py install --home $HOME/fitsio)
    - ln -s $HOME/astrometry.net astrometry
    - ln -s $HOME/fitsio/lib/python/fitsio .
    - ln -s $HOME/tractor-git/tractor .
    - ln -s $HOME/tractor-git/wise .

script:
    - export PYTHONPATH=${PYTHONPATH}:$(pwd)/py:$(pwd):$HOME/numpydoc
    - (cd doc && make)
    - (cd py && coverage run legacypipe/runbrick.py -b 2447p120 --zoom 1020 1070 2775 2815 --no-wise --force-all --survey-dir test/testcase3/ --outdir out-testcase3)

after_success:
    - coveralls

addons:
  apt:
    packages:
    - libnetpbm10
    - libnetpbm10-dev
    - wcslib-dev
    - libcfitsio3
    - libcfitsio3-dev
    #- python-numpy
    - swig
    - gsl-bin
    - python-sphinx
    - python-mock
    - python-matplotlib
    - python-scipy

# Ugh, travis's "precise" distro includes numpy 1.6.1

# python-numpydoc is only available in 'trusty' and later.
#    - python-numpydoc

# not whitelisted... needed?
#    - libgsl10-dev


cache:
  directories:
  - $HOME/astrometry.net
  - $HOME/tractor-git
  - $HOME/fitsio-git
  - $HOME/.local
