# Travis-CI.org build script

# container-based infrastructure
sudo: false
# need APT packages to get white-listed first;
#sudo: required

# install:
#   - sudo apt-get update -qq
#   - sudo apt-get install -y libnetpbm10 libnetpbm10-dev wcslib-dev libcfitsio3 libcfitsio3-dev python-numpy swig gsl-bin libgsl0-dev python-sphinx sphinx-common python-matplotlib python-scipy python-mock 
#   - sudo pip install numpydoc
# # python-numpydoc -- not available until Ubuntu 14.04 trusty

language: c
compiler:
  - gcc

#  - clang

#     - pkg-config --exists gsl
#     - pkg-config --modversion gsl
#     - export SYSTEM_GSL=yes
#     - ls /usr/include/wcslib*

#    - if [ ! -d "$HOME/astrometry.net" ]; then (cd $HOME; git clone https://github.com/dstndstn/astrometry.net.git); fi

before_script:
    - export WCSLIB_INC="-I/usr/include/wcslib-4.8.3"
    - export WCSLIB_LIB="-lwcs"
    - (cd $HOME; git clone https://github.com/dstndstn/astrometry.net.git)
    - (cd $HOME/astrometry.net && pwd && ls && make && make py)
    - if [ ! -d "$HOME/tractor-git" ]; then (cd $HOME; git clone https://github.com/dstndstn/tractor.git tractor-git); fi
    - (cd $HOME/tractor-git && make)
    - if [ ! -d "$HOME/fitsio-git" ]; then (cd $HOME; git clone https://github.com/esheldon/fitsio.git fitsio-git); fi
    - (cd $HOME/fitsio-git && python setup.py install --home $HOME/fitsio)
    - ln -s $HOME/astrometry.net astrometry
    - ln -s $HOME/fitsio/lib/python/fitsio .
    - ln -s $HOME/tractor-git/tractor .
    - ln -s $HOME/tractor-git/wise .


#     - pwd
#     - ls
#     - echo $HOME
#     - ls $HOME
#     - echo "$PYTHONPATH"
#     - ls -l
#     - python -c "import sys; print '\n'.join(sys.path)"
#     - python -c "import tractor; print tractor.__file__"

script:
    - export PYTHONPATH=${PYTHONPATH}:$(pwd)/py:$(pwd)
    - (cd doc && make)

addons:
  apt:
    packages:
    - libnetpbm10
    - libnetpbm10-dev
    - wcslib-dev
    - libcfitsio3
    - libcfitsio3-dev
    - python-numpy
    - swig
    - gsl-bin

# not whitelisted... needed?
#    - libgsl10-dev


cache:
  directories:
  - $HOME/tractor-git
  - $HOME/fitsio-git

#  - $HOME/astrometry.net
