# Travis-CI.org build script

# Default environment is Ubuntu 12.04.5 LTS "precise"
# which is pretty old.
# "trusty" is Ubuntu 14.04 LTS
#dist: trusty
# "xenial" is Ubuntu 16.04 LTS
#dist: xenial
# "bionic" is Ubuntu 18.04 LTS
dist: bionic

# use the newer container-based infrastructure
sudo: false

# python versions to test against...
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
# astrometry.util.timingpool error!
#  - "3.8"

install:
    # ubuntu's source extractor package renames the executable.
    #- mkdir ~/bin # exists
    - ln -s /usr/bin/sextractor ~/bin/sex
    - export PATH=${PATH}:~/bin
    - pip install Sphinx
    - pip install numpy
    - pip install scipy
    # matplotlib problem saving jpg (in python3.5 only):
    # https://github.com/ipython/ipython/issues/8052
    - pip install "Pillow<7"
    - pip install matplotlib
    - pip install numpydoc
    - pip install astropy
    - pip install photutils
    - pip install coveralls
    - pip install fitsio==1.1.1
    #- pip install --no-deps --upgrade git+https://github.com/esheldon/fitsio.git@v0.9.12#egg=fitsio
    #- pip install -v --no-deps --upgrade git+https://github.com/dstndstn/tractor.git@cython
    - pip install cython
    - git clone https://github.com/dstndstn/tractor.git
    - (cd tractor && python setup-cython.py install --with-ceres)

before_script:
    - if [ ! -d "$HOME/astrometry.net" ]; then (cd $HOME; git clone https://github.com/dstndstn/astrometry.net.git); fi
    - (cd $HOME/astrometry.net && git pull) || (rm -Rf $HOME/astrometry.net && cd $HOME && git clone https://github.com/dstndstn/astrometry.net.git);
    - (cd $HOME/astrometry.net && make && make py)

    - (cd $HOME && git clone https://github.com/legacysurvey/unwise_psf.git && cd unwise_psf && git checkout dr9.3)

    - mkdir -p $HOME/dust/maps
    - (cd $HOME/dust/maps && wget -c http://portal.nersc.gov/project/cosmo/temp/dstn/travis-ci/maps/SFD_dust_4096_ngp.fits)
    - (cd $HOME/dust/maps && wget -c http://portal.nersc.gov/project/cosmo/temp/dstn/travis-ci/maps/SFD_dust_4096_sgp.fits)
    - export DUST_DIR=$HOME/dust

script:
    - export PYTHONPATH=${PYTHONPATH}:$(pwd)/py:$HOME/astrometry.net:$HOME/unwise_psf/py
    - export PATH=${PATH}:$HOME/astrometry.net/blind
    - ls $HOME
    - ls $HOME/astrometry.net
    - (cd doc && make)
    - (cd py && coverage run test/runbrick_test.py travis psfex ceres && coverage run -a test/unit_tests.py)

after_success:
    - (cd py && coveralls debug)
    - (cd py && coveralls)
    - (cd py && ./codecov-upload.sh)

addons:
  apt:
    packages:
    - libnetpbm10
    - libnetpbm10-dev
    - netpbm
    - wcslib-dev
    - libcfitsio-dev
    - swig
    - gsl-bin
    - libgsl0-dev
    - libceres-dev
    - libcfitsio-bin # fpack
    - sextractor # for calibs
    - psfex # for calibs

cache:
  directories:
  - $HOME/astrometry.net
  - $HOME/dust
